linters:
  enable-all: false
  fast: false
  enable:
    - errcheck
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - gofumpt
  disable:
    - unused

run:
  timeout: 3m
