// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	RoleID    int64          `gorm:"column:role_id;type:int;primaryKey;autoIncrement:true" json:"role_id"`
	UserID    int64          `gorm:"column:user_id;type:int;not null;uniqueIndex:uk_user_role,priority:1" json:"user_id"`
	Role      string         `gorm:"column:role;type:varchar(255);not null;uniqueIndex:uk_user_role,priority:2" json:"role"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
