// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID     int32          `gorm:"column:user_id;type:int;primaryKey;autoIncrement:true" json:"user_id"`
	Username   string         `gorm:"column:username;type:varchar(255);not null;uniqueIndex:username,priority:1" json:"username"`
	Email      string         `gorm:"column:email;type:varchar(255);not null;uniqueIndex:email,priority:1" json:"email"`
	Password   string         `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Private    bool           `gorm:"column:private;type:tinyint(1);not null" json:"private"`
	Experience int32          `gorm:"column:experience;type:int" json:"experience"`
	Inviter    int32          `gorm:"column:inviter;type:int" json:"inviter"`
	CreatedAt  *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	LastActive time.Time      `gorm:"column:last_active;type:datetime" json:"last_active"`
	Avatar     string         `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Signature  string         `gorm:"column:signature;type:text" json:"signature"`
	Background string         `gorm:"column:background;type:varchar(255)" json:"background"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
