// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.
package code

// codeToString use a map to store the string representation of Code
var codeToString = map[Code]string{
	InternalError:   "Internal error",
	UnknownError:    "Unknown error",
	InvalidParams:   "Invalid params",
	InvalidToken:    "Invalid token",
	InvalidUserName: "Invalid user name",
}
