// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.

export const enum ErrorCode {
  InternalError = 10000,
  UnknownError,
  AuthErrorTokenHasBeenBlacklisted,
  AuthErrorTokenIsInvalid,
  RequestErrorInvalidParams,
  DatabaseErrorRecordCreateFailed,
  DatabaseErrorRecordNotFound,
  DatabaseErrorRecordPatchFailed,
  UserErrorRegisterNotAllowed,
  UserErrorInvalidUsername,
  UserErrorInvalidPassword,
  UserErrorInvalidEmail,
  UserErrorInvalidInvitationCode,
  UserErrorInvitationCodeHasReachedLimit
}
