version: "3.8"

services:
  db:
    image: mysql:8.4.1
    container_name: some-mysql
    restart: always
    ports:
      - "5432:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nuxbt
      TZ: Asia/Shanghai

  redis:
    image: redis:7.2.5
    container_name: some-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  oss:
    image: bitnami/minio:2024.7.13
    container_name: some-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ChYm7ufIwNAOzq6PQPCA
      MINIO_SECRET_KEY: udicP52IwRbmo2hf6lFvjUS7NP5BhlAdsGNIuDE5
      MINIO_DEFAULT_BUCKETS: nuxbt:public
