name: CI-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

jobs:
  unit-test:
    strategy:
      matrix:
        os-version: [ "ubuntu-latest" ]

    runs-on: ${{ matrix.os-version }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: nuxbt
        ports:
          - "3306:3306"
      redis:
        image: redis
        options: >- # wait until redis has started
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
        ports:
          - 6379:6379
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: ChYm7ufIwNAOzq6PQPCA
          MINIO_SECRET_KEY: udicP52IwRbmo2hf6lFvjUS7NP5BhlAdsGNIuDE5
          MINIO_DEFAULT_BUCKETS: nuxbt:public
        ports:
          - "9000:9000"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: |
          go test ./...
